language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install: pip install git+https://github.com/ageitgey/face_recognition_models

install: pip install -r requirements.txt --use-mirrors

script: make test
