version: '2.3'

services:
  face_recognition:
    image: face_recognition
    container_name: face_recognition
    working_dir: /face_recognition/examples
    build:
      context: .
    command: python3 -u find_faces_in_picture_cnn.py
    volumes:
      - ./:/face_recognition
    runtime: nvidia #Comment this line if you don't have nvidia-docker installed (requires GPU)